### ISSUE TITLE
Crashes when you enter Iceika

### ISSUE THREAD

**Issue by Fuheshka** [NicosaurusRex99/DivineRPG#100]
Forge version: 1.12.2-forge1.12.2-14.23.5.2847
DivineRPG version: DivineRPG-1.12.2-1.5.2
https://gist.github.com/Fuheshka/9bfab11fcbaf8c0de45c65464432e5f7

**Comment by Fuheshka** [comment]
I was now looking for what could be the problem and it seems I found what it is. Divine RPG is in conflict with the Apotheosis mod.

**Comment by AstralScourge** [comment]
I'll check it out myself, but just reading the description of Apotheosis that probably shouldn't be happening.
