### ISSUE TITLE
Bricks recipes are giving small amounts them

### ISSUE THREAD

**Issue by Martin414** [NicosaurusRex99/DivineRPG#101]
Mod version: DivineRPG-1.12.2-1.5.2.jar

What happened: All types of bricks in the mod are giving only one item per recipe, and I think they should give more. Example: 1x Diamond Bricks require 3x Stone Bricks and 1x diamond.
![recipe](https://user-images.githubusercontent.com/52965556/78172954-3c3f9c80-7457-11ea-9188-c9b14a1fdee5.png)
In my opinion they should give me 4x Diamond Bricks ore 3x.

Potential fix: Change output of the recipes.

**Comment by SofiaAViesti** [comment]
I would like to extend this post's request towards the stone minibricks as well, which currently yields on a 9-1 ratio of stone bricks per stone minibrick block, and its rupee variation costing a whole rupee ingot per block sounds a little off given their rarity.

**Comment by NicosaurusRex99** [comment]
we liked the idea
