### ISSUE TITLE
Infusion Table Issue

### ISSUE THREAD

**Issue by SofiaAViesti** [NicosaurusRex99/DivineRPG#102]
Hey guys, I've spent some time testing all of the recipes in the Infusion Table in a fresh new installation to see which ones are working by default and which ones aren't. It was a little difficult at first since not all recipes are available on the Wiki (also some are a little different), but I took the effort and checked them all. I will be linking a .txt file with the results.

TL;DR - Apparently all weapons from Quadro tier upwards aren't working. That's all.
[InfusionTableResults.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4422906/InfusionTableResults.txt)

(I just took this print of a cannon turning into a dispenser because I thought it was kinda funny)
![karos cannon](https://user-images.githubusercontent.com/62922387/78284490-e4a43e00-74f5-11ea-8889-229a348e73a8.png)

Forge version: 14.23.5.2768 and 14.23.5.2847
DivineRPG version: 1.5.2 (mc 1.12.2)
Link to crash log if applicable: --

Steps to reproduce:
1. Go to Vethea
2. Find an Infusion Table
3. Try the recipes that didn't work

What I expected to happen: --

What happened instead: --

Potential fix: --

**Comment by AstralScourge** [comment]
Known issue, fixed for next version (including the karos cannon one).
