### ISSUE TITLE
Pardimal and karrow arrows don't have a name

### ISSUE THREAD

**Issue by Unhook** [NicosaurusRex99/DivineRPG#103]
Forge version: 14.23.5.2847

DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar): DivineRPG-1.12.2-1.5.2.jar

What I expected to happen:
Them to have names.

What happened instead:
They don't have names.

Potential fix:
Add localization

**Comment by AstralScourge** [comment]
Fixed for next version
