### ISSUE TITLE
Killing multiple The Ancient with Mob Crusher from Industial Forgoing causes crash

### ISSUE THREAD

**Issue by PsyCrow1976** [NicosaurusRex99/DivineRPG#105]
Forge version: 
DivineRPG version: DivineRPG-1.12.2-1.5.2.jar
crash file from single plater : https://pastebin.com/L0Spgw7h
using divineRPG in Celestial Journey version 1.1.3

Steps to reproduce:
Create single player world
place a mob crusher from industrial forgoing with a max range upgrade
spawn in 2 ore more The Ancient

What I expected to happen:
It kills all The ancient

What happened instead:
games crashed (both single player and multiplayer)

additional info : NicosaurusRex99 watched my stream when this happened multiple times

**Comment by PsyCrow1976** [comment]
I did some more test and placing a single The Ancient can also cause the crash..

i travelled to the Nether and spawned multiple King of Sorcheres.. and they where killed with no issies by the Mob Crusher.

**Comment by AstralScourge** [comment]
This seems to be a Forge bug and not on our side nor Industrial Foregoing. However I'll see if I can test checking if it's an instance of fake player before applying a potion effect, not sure if that will work however
