### ISSUE TITLE
Incorrect saturation values for foods

### ISSUE THREAD

**Issue by bluebear94** [NicosaurusRex99/DivineRPG#106]
Forge version: 14.23.5.2847
DivineRPG version: DivineRPG-1.12.2-1.5.2.jar
Link to crash log if applicable: n/a

Steps to reproduce:
1. Inspect the hunger and saturation values of one of the foods in DivineRPG. This can be done with a mod such as AppleSkin. For this example, I'll be using the Chicken Dinner, which claims to give 20.0 saturation (shanks or points intended?).

What I expected to happen: AppleSkin displays either 10 or 20 shanks (= 20 or 40 points) of saturation for the food.

What happened instead: AppleSkin displays 400 (!) shanks of saturation for the food.

Potential fix: Unknown

**Comment by AstralScourge** [comment]
I'll look into it

**Comment by AstralScourge** [comment]
Fixed in 8f10e3b. Issue was on our end as the saturation parameter is a ratio instead of a flat value but we didn't treat it as such.
