### ISSUE TITLE
Vethea structure generated when using twighlight clock

### ISSUE THREAD

**Issue by velocityraptor-real** [NicosaurusRex99/DivineRPG#107]
Forge version: 
DivineRPG version: commit https://github.com/NicosaurusRex99/DivineRPG/commit/a0bc1d3831513d09c2209486b2a459e431ee247c

Steps to reproduce:
https://www.youtube.com/watch?v=93aFU97vkoM
1. Use twighlight clock

What I expected to happen:
Portal being lit
What happened instead:
Vethea structure generating
Potential fix:
Idk

**Comment by velocityraptor-real** [comment]
![2020-04-05_16 05 59](https://user-images.githubusercontent.com/56190563/78500603-ab6b0880-7757-11ea-9c1c-11d7c1e32b3b.png)
it also lights the fire

**Comment by AstralScourge** [comment]
Removed in d0aefd1
