### ISSUE TITLE
Repair items on the anvil

### ISSUE THREAD

**Issue by Locomenmod** [NicosaurusRex99/DivineRPG#110]
Forge version: 2768
DivineRPG version: divinerpg-1.12-1.5.3.jar

In the modification, items cannot be repaired on the anvil using the materials from which they are crafted. That is, you will always have to craft new ones.

**Comment by Oshi41** [comment]
@Immortallis1 
ToolMaterialMod
We are registering null items because of Object Holders

**Comment by NicosaurusRex99** [comment]
@Immortallis1 im fairly sure you fixed this. just checking did you?

**Comment by AstralScourge** [comment]
Yes, this was fixed as of efac42b
