### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Locomenmod** [NicosaurusRex99/DivineRPG#111]
Add keys to translate the description of the armor's abilities to lang files. Also add tolltips that are not included in lang files previously.

Example of keys for lang files:

> tooltip.armor_info.fire_protection=Fire Protection
> tooltip.armor_info.no_fall=No Fall Damage
> tooltip.armor_info.fly=Flight
> tooltip.armor_info.speed=#x Movement Speed
> tooltip.armor_info.melee_damage=+# Melee Damage
> tooltip.armor_info.ranged_damage=+#% Ranged Damage
> tooltip.armor_info.hunger=Refills Hunger
> tooltip.armor_info.damage_reduction=#% Damage Reduction
> tooltip.armor_info.jump_height=#x Jump Height
> tooltip.armor_info.ore_drops=+# Twilight Ore Drops
> tooltip.armor_info.health_regen=Health Regeneration
> tooltip.armor_info.underwater_health_regen=Health Regenerates Underwater
> tooltip.armor_info.block_protection=Block Damage Protection
> tooltip.armor_info.night_vision=Night Vision
> tooltip.armor_info.explosion_protection=Explosion Protection
> tooltip.armor_info.ranged_protection=#% Ranged Damage Protection
> tooltip.armor_info.melee_protection=#% Melee Damage Protection
> tooltip.armor_info.arcana_protection=+#% Arcana Damage Protection
> tooltip.armor_info.underwater=Breathe Underwater
> tooltip.armor_info.scythe_damage=#x Scythe Damage
> tooltip.armor_info.swim=Swim Faster
> tooltip.armor_info.wither_protection=Wither Protection
> tooltip.armor_info.arcana_regen=Arcana Regeneration
> tooltip.armor_info.poison_protection=Poison Resistance
> tooltip.armor_info.freeze=Slows Hostile Mobs Within 6 Blocks
> tooltip.armor_info.haste=Increased Mining Speed

**Comment by Oshi41** [comment]
Take a look there
https://github.com/NicosaurusRex99/DivineRPG/commit/2d5a3514ed836e837f2e33f707dc778f3190670c

**Comment by NicosaurusRex99** [comment]
ok to close this?

**Comment by Locomenmod** [comment]
I think not yet.

**Comment by Locomenmod** [comment]
On the server, messages and boss bars are not translated, but remain in English, although everything works fine in a singleplayer.

**Comment by Locomenmod** [comment]
With the transition to the new format, everything now works correctly
