### ISSUE TITLE
Server crashes on startup with sponge installed

### ISSUE THREAD

**Issue by bigenergy** [NicosaurusRex99/DivineRPG#113]
Forge version: 2847
DivineRPG version: DivineRPG-1.12.2-1.6
Link to crash log if applicable: https://gist.github.com/bigenergy/c16b7fe9b0f012342598f3a2054a570b

Steps to reproduce:
1. install spongeforge (any version) 
2. start server
3. get crash

What I expected to happen:
the server will start

What happened instead:
Server crashes on startup with sponge installed

**Comment by NicosaurusRex99** [comment]
Sponge isnt supported. it breaks too many things

**Comment by bigenergy** [comment]
I'm sad(
but I think you should write somewhere about it

**Comment by AstralScourge** [comment]
Will try to fix this, however no guarantees

**Comment by AstralScourge** [comment]
Potentially fixed in 5e0d75d

**Comment by NicosaurusRex99** [comment]
Can you test it on this build @bigenergy  [https://www.dropbox.com/s/f00iqv7la53tcbp/DivineRPG-1.12.2-SPONGEFORGE%20FIX.jar?dl=0](url)

**Comment by Locomenmod** [comment]
I think it fix problem
![изображение](https://user-images.githubusercontent.com/38961139/80013462-97edca80-84d7-11ea-88dc-b4025b61f94e.png)

**Comment by bigenergy** [comment]
> Can you test it on this build @bigenergy [https://www.dropbox.com/s/f00iqv7la53tcbp/DivineRPG-1.12.2-SPONGEFORGE%20FIX.jar?dl=0](url)

Thanks for the fix, this version seems to work on a sponge.
I’ll check more carefully, maybe there are still errors on the sponge, I will write about it

**Comment by Locomenmod** [comment]
If there are new errors, create another issue.
