### ISSUE TITLE
Vethea refuses to load

### ISSUE THREAD

**Issue by Unhook** [NicosaurusRex99/DivineRPG#114]
Forge version: 
DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar): DivineRPG-1.12.2-1.6.jar
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Try to enter Vethea

What I expected to happen:
Be able to enter Vethea

What happened instead:
Doesn't load. Just stays on the loading screen

Potential fix: (If you understand modding, dont worry if you dont)

**Comment by Locomenmod** [comment]
Fixed in 5e0d75dbd0a7588a3dbd97eedd137ff3f74f6993
