### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by bigenergy** [NicosaurusRex99/DivineRPG#115]
Forge version: 2847
DivineRPG version: DivineRPG-1.12.2-SPONGEFORGE FIX
Link to crash log if applicable: https://gist.github.com/bigenergy/cdede2f9e2d94738c1fcce5b0222124e

Steps to reproduce:
I can’t determine why, but it happens sometimes, possibly due to the installed sponge

**Comment by AstralScourge** [comment]
Potentially fixed in a00a137. Fix will be in the next patch, test that out when it comes

**Comment by Locomenmod** [comment]
https://www.dropbox.com/s/mpmp23asjvo193t/DivineRPG-1.12.2-issue-115.jar?dl=0

**Comment by AstralScourge** [comment]
@bigenergy can you test if the issue occurs in the above build

**Comment by bigenergy** [comment]
Fixed (at least I have not yet managed to catch the same error), thx
