### ISSUE TITLE
Crash in the End by Ayeraco

### ISSUE THREAD

**Issue by TimeConqueror** [NicosaurusRex99/DivineRPG#116]
Forge version: 1.12.2-2847
DivineRPG version: 1.12.2-1.5.3
Link to crash log if applicable:
https://pastebin.com/2BUHJYNX

Crash is not mine.
The guy entered the end, spawned Ayeraco, killed Purple one, then was killed, entered end again and catched that exception.

**Comment by velocityraptor-real** [comment]
Why are you using 1.5.3?
Try recreating the bug in 1.6.0.1. See ,if it still crashes

**Comment by TimeConqueror** [comment]
Checked, the same

**Comment by NicosaurusRex99** [comment]
can we have the new log

**Comment by TimeConqueror** [comment]
https://pastebin.com/wGqJ4rsk

**Comment by NicosaurusRex99** [comment]
is this server or single player?

**Comment by TimeConqueror** [comment]
Singleplayer

**Comment by NicosaurusRex99** [comment]
i have my doubts but does this fix your issue? https://www.dropbox.com/s/eljpwc4u8izo978/DivineRPG-1.12.2-ARCANAFIX.jar?dl=0

**Comment by NicosaurusRex99** [comment]
This file should fix your issue. please let us know if it does https://www.dropbox.com/s/kswc2k4iqvrw7py/DivineRPG-1.12.2-AYERACOFIX.jar?dl=0

**Comment by NicosaurusRex99** [comment]
Fixed in 578004f

if you find this issue again please reopen it
