### ISSUE TITLE
Internal server error 2

### ISSUE THREAD

**Issue by bigenergy** [NicosaurusRex99/DivineRPG#117]
This is a sequel https://github.com/NicosaurusRex99/DivineRPG/issues/115

It seems that if the player’s profile does not exist on the server, then he will get an error
https://gist.github.com/bigenergy/0850332a8917d3e831e8ba7fc6a638a7

**Comment by bigenergy** [comment]
Other players can kick with the same error, for example, I just stood on the server, another player came in and kicked me from the server

**Comment by NicosaurusRex99** [comment]
Can you please tell me if this fixes your issue https://www.dropbox.com/s/eljpwc4u8izo978/DivineRPG-1.12.2-ARCANAFIX.jar?dl=0

**Comment by bigenergy** [comment]
> Can you please tell me if this fixes your issue https://www.dropbox.com/s/eljpwc4u8izo978/DivineRPG-1.12.2-ARCANAFIX.jar?dl=0

fixed
