### ISSUE TITLE
divine rpg crash in another dimension

### ISSUE THREAD

**Issue by DeadUn1corn** [NicosaurusRex99/DivineRPG#119]
Forge version: 
DivineRPG version: (DivineRPG-1.12.2-1.6.0.1)
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. https://gist.github.com/DeadUn1corn/b678f5893f09e9508fc000eb30cf8353

What I expected to happen:i just killed boss and went to the new dimension and my game died.

What happened instead:whenever i go to other dimension my games crash.I see this flying mob and my minecraft stop working.

Potential fix: (can i somehow remove this mobs )

**Comment by NicosaurusRex99** [comment]
Its an incompatability with reliquary

**Comment by NicosaurusRex99** [comment]
@Oshi41 was it you who made the divine ghast class?

**Comment by NicosaurusRex99** [comment]
Wrong button...

**Comment by DeadUn1corn** [comment]
Thx you so much <3 Much love
