### ISSUE TITLE
Crash Upon Entering Dimensions (Celestial Journey 2.0.4)

### ISSUE THREAD

**Issue by coffeeordeath** [NicosaurusRex99/DivineRPG#120]
Forge version: 14.23.5.2847
DivineRPG version: divinerpg1.12.2 - 1.6.0.1
Link to crash log if applicable: https://gist.github.com/coffeeordeath/78b68f5c87df2fbdad94ee0c9cff7e39

Steps to reproduce:
1. Enter a dimension (Eden, The End, Wildwood)

What I expected to happen: Nothing. Normal gameplay

What happened instead: Crashed game for player who entered dimension and looked at a certain entity. In the log posted above, it was the Ender Triplets

The server we run has had multiple issues with people getting crashes upon loading into the End, Eden, and Wildwood. This is an example of one that just happened that to myself, though i do have numerous others.

**Comment by Oshi41** [comment]
Take a look here
https://github.com/NicosaurusRex99/DivineRPG/issues/119

**Comment by coffeeordeath** [comment]
i suppose i didnt understand where u had posted a fix. Is this released already? should i have my people update or something?

**Comment by AstralScourge** [comment]
@coffeeordeath This means that it will be fixed next patch, because the commit he posted was two days ago and the last released version was a bit before that

**Comment by NicosaurusRex99** [comment]
Fixed in update 1.6.0.2
