### ISSUE TITLE
Shuriken craft and Melee Enchanted Archer

### ISSUE THREAD

**Issue by JohnnyAnakonda** [NicosaurusRex99/DivineRPG#121]
Forge version: 14.23.5.2847
DivineRPG version: 1.12.2 (1.6.1)

What happened instead:
1.When i crafting Shurikens, i gets only 1 of them instead 20
2.Enchanted Archer doesn't use bow, and he just attack you on melee

**Comment by NicosaurusRex99** [comment]
Shuriken fixed bc1c291
