### ISSUE TITLE
Mortum Ore doesn't generate

### ISSUE THREAD

**Issue by Unhook** [NicosaurusRex99/DivineRPG#122]
Forge version: 
DivineRPG version: DivineRPG-1.12.2-1.6.0.2.jar
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Go to mortum

What I expected to happen:
Mortum ore to generate

What happened instead:
Mortum ore doesn't generate

Potential fix: (If you understand modding, dont worry if you dont)

**Comment by NicosaurusRex99** [comment]
Have you tried to raise the values in the config?

**Comment by Unhook** [comment]
https://www.youtube.com/watch?v=qZyGEF7Pfds&t=355s 
5:00. 30 chunks quarried and 0 mortum ore. I doubt it generates at all

**Comment by Oshi41** [comment]
Mortum ore will generated in twilight stone lakes on surface
