### ISSUE TITLE
Ammo type and other "T-Pose" bosses

### ISSUE THREAD

**Issue by JohnnyAnakonda** [NicosaurusRex99/DivineRPG#126]
Forge version: 14.23.5.2847
DivineRPG version: 1.6.2

What happened instead:
1.Game doesn't show wich one ammo used one or other ranged weapon https://imgur.com/a/fNY4WbB
2.In previous post i told that Vamacheron boss dont have any animation, but just now, i see that every Divine RPG bosses [Except: Karot, Twilight Archer and Vethea bosses] dont have any animations

**Comment by NicosaurusRex99** [comment]
ive already fixed 2nd issue
