### ISSUE TITLE
Update maps with DivineRPG 1.7.10 > 1.12.2

### ISSUE THREAD

**Issue by WareZ57** [NicosaurusRex99/DivineRPG#128]
Hello,

I have no problem with the mods itself.

My problem is that my server was under version 1.7.10 which use DivineRPG, I used items for the decorations of maps.

Now that I want to change version to go to 1.12.2 Minecraft refuses to launch the maps because it was under 1.7.10 and ask me to launch it in version 1.8 before being able to use it on 1.12.2.
That's the problem, divineRPG your step was to develop under version 1.8 (not found on the web) unless I'm mistaken?

Do you have a 1.8 version of the mod? Or another alternative to avoid having to redo a complete map?

(80% of the maps use DivineRPG)

Thank you.

**Comment by NicosaurusRex99** [comment]
Sadly we do not have a 1.8 version and wont be making one. you might be able to do something with MCEdit but i wouldnt count on it

**Comment by WareZ57** [comment]
Don't work, i use other map thanks you.
