### ISSUE TITLE
Divine Armor give Flight

### ISSUE THREAD

**Issue by UnknownLukito** [NicosaurusRex99/DivineRPG#131]
Forge version: 14.23.5.2847
DivineRPG version: DivineRPG-1.12.2-1.6.2.1.jar

Steps to reproduce:
1. Wear 1 set of angel armor (gives flight)
2. Double space (to fly)
3. Drop down and change to divine armor
3. Double space (to fly)

What I expected to happen: No Flight

What happened instead: Flight

**Comment by NicosaurusRex99** [comment]
Fixed by @Oshi41 in 0a0f8e5
