### ISSUE TITLE
Wrong Iceika dimension ID

### ISSUE THREAD

**Issue by ExcisionEdits** [NicosaurusRex99/DivineRPG#132]
Forge version: 1.12.2 - 14.23.5.2847
DivineRPG version: DivineRPG-1.12.2-1.6.2.1

Had an issue with Iceika dimension on a server. I couldn't load into it due to its ID being different in my client config (it was 7 for some reason while default one is 425). I haven't changed anything in my configs so I thought it could be some sort of a bug?

**Comment by AstralScourge** [comment]
The default used to be 7, now it is 425 (the default being 7 was an oversight to begin with). Change the value in your config to 7
