### ISSUE TITLE
Overly excessive rainbour spawning

### ISSUE THREAD

**Issue by guitarpick38** [NicosaurusRex99/DivineRPG#133]
Forge version: 14.23.5.2847
DivineRPG version: DivineRPG-1.12.2-1.6.2.1

In any dark area I will encounter an extreme amount of rainbours spawning, this fills up the entity count and causes my game to lag a bit
[here is a screenshot of how many can appear as well as a screenshot of how many entities are in the area with F3](https://imgur.com/a/tsY3Ump)

**Comment by AstralScourge** [comment]
Haven't seen any evidence of this. Also 129 is not a high entity count
