### ISSUE TITLE
Server lag when entering portal

### ISSUE THREAD

**Issue by MCUmbrella** [NicosaurusRex99/DivineRPG#135]
Forge version: 1.12.2-14.23.5.2846
DivineRPG version: DivineRPG-1.12.2-1.6.2.1.jar
Link to crash log if applicable: Not crash but I have a Spark tick profile(https://spark.lucko.me/#2DMAimNv4o)

Steps to reproduce:
1. Create a DivineRPG portal(I created portal to Wildwood)
2. Enter the portal

What I expected to happen: Normally teleported to the world

What happened instead: Server lag for 6~7 seconds and teleported to the world(for example: "Can't keep up! Did the system time change, or is the server overloaded? Running 6109ms behind, skipping 122 tick(s)")

Potential fix:

**Comment by NicosaurusRex99** [comment]
This is most likely caused by Sponge 
`Entity.redirect$zeh000$spongeImpl$onEntityCollideWithBlockState()99.45%`

**Comment by MCUmbrella** [comment]
Problem solved. It caused by Eclipse Openj9 VM so now Im running my server under Oracle's JVM.

**Comment by NicosaurusRex99** [comment]
cool cool
