### ISSUE TITLE
suggestion: config for weapon stats

### ISSUE THREAD

**Issue by Shattered2909** [NicosaurusRex99/DivineRPG#136]
i apologize if this does not belong here, i asked about this on your discord and got no reply.

how do you feel about adding a config for tweaking weapon (and armor?) stats? i am making a modpack where divine RPG will be the late game so mobs will be buffed a ton which makes the weapons quite bad against them, so i would like to buff them too.

**Comment by NicosaurusRex99** [comment]
no reply would be because we are a small team that arent on all the time
