### ISSUE TITLE
Armor durability

### ISSUE THREAD

**Issue by Shaymiestar** [NicosaurusRex99/DivineRPG#137]
In the original Divine RPG some armor sets had infinite durability, but in this update they all have limited durability. This is really inconvenient and if possible, I'd like at least a config option to change it to how it was. Sorry if this is not the right place, I don't really use github.

**Comment by AstralScourge** [comment]
How isn't it convenient? The armor shouldn't break unless you get hit all the time, and you can repair it or just put unbreaking on it.

**Comment by NicosaurusRex99** [comment]
Without change there is no room for innovation
