### ISSUE TITLE
Dimensions make me crash

### ISSUE THREAD

**Issue by Zack7292** [NicosaurusRex99/DivineRPG#138]
Forge version: 2854
DivineRPG version: DivineRPG-1.6.3.1
Link to crash log if applicable: https://pastebin.com/g4qyHky7

Steps to reproduce:
1. install this modpack (i have no idea what mod cause this with it but its one in it): https://www.curseforge.com/minecraft/modpacks/infinitely-exploring 
2. join any dimensions from this mod (you can use the feather from custom NPC to go faster)

What I expected to happen:
loading the dimensions normaly

What happened instead:
it crashed

Potential fix: (If you understand modding, dont worry if you dont)
idk, fix it lol

**Comment by NicosaurusRex99** [comment]
From this log, i can tell
Level dimension: 0 (Overworld)
Level game mode: ~~ERROR~~ NullPointerException: null (You dont have a game mode)
o not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar) (You have foamfix but havent tried doing what it suggests)

**Comment by Zack7292** [comment]
ok i'll try and look thx for the help :)

**Comment by Zack7292** [comment]
now the crash have changed: https://pastebin.com/f2NwFiWu

**Comment by NicosaurusRex99** [comment]
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump what is this?

**Comment by Zack7292** [comment]
no idea

**Comment by Zack7292** [comment]
its the twitch launcher's ram automatic settings

**Comment by NicosaurusRex99** [comment]
That log says you still have foamfix enabled.

**Comment by Zack7292** [comment]
literally removed FoamFix this time: https://pastebin.com/sKPWVyUf

**Comment by NicosaurusRex99** [comment]
@Oshi41 @AstralScourge any ideas?

**Comment by AstralScourge** [comment]
Can you post Project Vibrant Journeys config file?

**Comment by Zack7292** [comment]
here: https://pastebin.com/7ut72Gs4   (sorry for being late forgot to check)

**Comment by AstralScourge** [comment]
Your animals density is 0, and it's mentioned over there that it can cause a crash at /OrderedChaos-Dev/ProjectVibrantJourneys/issues/87. The mod dev closed without confirming but the poster seems to have experience with forge and other projects so I'll take his word for it

Either change animal density in Vibrant Journeys to 100, or remove the mod

**Comment by Zack7292** [comment]
It has work i've put it to 100 and your dimension generate normally now! Thx for the help :D kinda weird project vibran journey make your dimensions crash tho?

**Comment by NicosaurusRex99** [comment]
it makes many dimensions crash

**Comment by Zack7292** [comment]
for all the one in my modpack, it's the only one!
