### ISSUE TITLE
Mortum bedrock layer

### ISSUE THREAD

**Issue by Serafimsd** [NicosaurusRex99/DivineRPG#139]
Mortum Chunk Generator generate air instead bedrock.
![HW6PwFiiWm8](https://user-images.githubusercontent.com/7882078/84254476-f28bc600-ab19-11ea-941b-34d408e35c57.jpg)

**Comment by NicosaurusRex99** [comment]
twilight dimensions arent supposed to have bedrock

**Comment by AstralScourge** [comment]
I will look into it

**Comment by AstralScourge** [comment]
Fixed in 49d51d3
