### ISSUE TITLE
Mobs not spawning on their dimensions.

### ISSUE THREAD

**Issue by ghost** [NicosaurusRex99/DivineRPG#141]
Forge version: 1.12.2 - 14.23.5.2854
DivineRPG version: divinerpg-1.6.4.jar
Link to crash log if applicable: no crash

Steps to reproduce:
I have a lot of other mods installed so this is probably a compatibility issue but id like to know the steps i could take to fix this, so basically, mobs spawn regularly on the overworld, but they dont spawn in their dimensions like iceika. I tried messing with the config but didnt find anything relevant.

**Comment by ghost** [comment]
[list.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4810627/list.txt)
This is my mod list, i have no idea how to publish it on curse forge

**Comment by NicosaurusRex99** [comment]
Dont use DrZharks custom mob spawner, we recommend mcjtys in control

**Comment by ghost** [comment]
as i understand, the mo creatures mod need the custom mob spawner, can mcjtys work with mo creatures instead of CMS? mo creature livens up the game and id hate to see that one go

**Comment by NicosaurusRex99** [comment]
Im not sure

**Comment by ghost** [comment]
i know you are not the creator of in control, but do you know if anyone has shared a mo creatures adapted config file?

**Comment by NicosaurusRex99** [comment]
i do not sorry

**Comment by ghost** [comment]
not even an in control config file with your dimensions and their spawn rules?

**Comment by NicosaurusRex99** [comment]
i think it gets default spawn rates and stores them in a config but i may be wrong

**Comment by ghost** [comment]
in control's files are empty, it makes me do them from 0

**Comment by NicosaurusRex99** [comment]
[https://github.com/NicosaurusRex99/DivineRPG/blob/1.12.2/src/main/java/divinerpg/registry/EntitySpawnRegistry.java#L128](url)
This is our spawn registry.
First number is max spawned, second is min spawned, third number is the amount of times it tries to spawn mobs

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/67246494/85245524-b51e1700-b3fc-11ea-959c-85b5a717b762.png)

![image](https://user-images.githubusercontent.com/67246494/85246112-8ef97680-b3fe-11ea-9685-2c9c50f785a9.png)

while playing with the  CMS config i see that some biome references dont appear, the only biome that appears is skythern and yet nothing spawn, is it possible that the reference to the biome is wrong?

**Comment by NicosaurusRex99** [comment]
CMS does some weird stuff.

**Comment by NicosaurusRex99** [comment]
Closed since CMS breaks stuff and lack of inactivity
