### ISSUE TITLE
Tar Pools generating in the Betweenlands

### ISSUE THREAD

**Issue by Shattered2909** [NicosaurusRex99/DivineRPG#142]
Forge version:  forge-14.23.5.2847
DivineRPG version: DivineRPG-1.6.4.jar

For some reason it is generating in the Betweenlands, maybe in other dims as well. I disabled the config option for Tar to generate in the Overworld, apparently it doesn't matter for others.

**Comment by AstralScourge** [comment]
Betweenlands adds its own tar. https://the-betweenlands.fandom.com/wiki/Tar
Are you sure this is not the tar you are seeing?

**Comment by NicosaurusRex99** [comment]
can confirm this is not our tar

**Comment by AstralScourge** [comment]
@Shattered2909 Show a screenshot of the tar lake

**Comment by Shattered2909** [comment]
Oh wait, maybe there's an issue with both mods using the same name for Tar so one overwrites the other. It's similar with the Betweenlands Rubber and GT Rubber.

Is there any way of fixing that from my side?

**Comment by AstralScourge** [comment]
What makes you think it's actually overwriting tar and that it's not just Betweenlands tar?
Could you post a picture of the tar lake please? Probably the best way to find out

**Comment by Shattered2909** [comment]
Well it is the Tar gen in the Betweenlands but it looks like the DivineRPG Tar (because they both have the same name and there's a weird priority system) so when I pick it up it's BWL Tar in the Bucket, in a Tank is also looks like BWL Tar but when placed in the world it is DivineRPG Tar

**Comment by AstralScourge** [comment]
I tried it myself there does seem to be an issue. Not sure on the specifics yet

**Comment by AstralScourge** [comment]
Fixed in 03ad07a, had to rename the fluid though because that's how Forge works I guess
