### ISSUE TITLE
Crash on CatServer

### ISSUE THREAD

**Issue by Coloryr** [NicosaurusRex99/DivineRPG#143]
Forge version: 14.23.5.2854
DivineRPG version: DivineRPG-1.6.4.0
Link to crash log if applicable: https://paste.ubuntu.com/p/4zBtB92bRR/

Steps to reproduce:
1. join the DivineRPG world

What I expected to happen:
It's look like no work well on Catserver

I try use `super.setAttackTarget(target);` but it can't work

**Comment by NicosaurusRex99** [comment]
update to the latest Divine 1.6.4 and let me know it the issue is still present. the log shows version 1.6.3.1

**Comment by Coloryr** [comment]
well,that was same crash
https://paste.ubuntu.com/p/HnWq9t4FFT/

**Comment by NicosaurusRex99** [comment]
I have tweaked the issued class in 10bb552 however. We will NEVER officially support third party software especially if it breaks Mojangs EULA
