### ISSUE TITLE
forg 1.12.2

### ISSUE THREAD

**Issue by Realitet** [NicosaurusRex99/DivineRPG#144]
Forge version: 
DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar)
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. 

What I expected to happen:

What happened instead:

Potential fix: (If you understand modding, dont worry if you dont)

**Comment by NicosaurusRex99** [comment]
@Realitet if you had a crash please fill out this form and reply. if not i request that you close the report

**Comment by NicosaurusRex99** [comment]
NVM issue is over at #145
