### ISSUE TITLE
Crach

### ISSUE THREAD

**Issue by Realitet** [NicosaurusRex99/DivineRPG#145]
Forge version: 1.12.2
DivineRPG version: 1.6.3.1

[crash-2020-06-29_09.41.00-server.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4844039/crash-2020-06-29_09.41.00-server.txt)

Steps to reproduce:
1. 

What I expected to happen:
[crash-2020-06-29_09.41.00-server.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4844002/crash-2020-06-29_09.41.00-server.txt)

What happened instead:
[crash-2020-06-29_09.41.00-server.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4844012/crash-2020-06-29_09.41.00-server.txt)
[debug-4.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/4844013/debug-4.log.gz)

Potential fix: (If you understand modding, dont worry if you dont)
[2020-06-29-2.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/4844065/2020-06-29-2.log.gz)

**Comment by NicosaurusRex99** [comment]
Does this issue occur every time you use the portal or was it a one time crash?

**Comment by Realitet** [comment]
Always

**Comment by NicosaurusRex99** [comment]
Is this in singleplayer? or does it use some third party server tool like sponge or cauldron?

**Comment by velocityraptor-real** [comment]
the modpack is full of errors...

**Comment by Realitet** [comment]
Single

**Comment by velocityraptor-real** [comment]
if you update to 1.6.4.1 you will prevent the tar issue
But i can't find the direct issue causing you to crash

**Comment by NicosaurusRex99** [comment]
my thought is Why are you using `/jtp x, y, z <dimension>` instead of the portal or `/forge setDimension` command?

**Comment by Realitet** [comment]
In what sense

**Comment by NicosaurusRex99** [comment]
so forge has a built in command `/forge setDimension` im just suggesting that you use the forge command to test if the issue is with `/jtp` or with our block

**Comment by NicosaurusRex99** [comment]
Closed due to inactivity.
Alternative methods of going to dimensions are in place as is
