### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FrozenYT** [NicosaurusRex99/DivineRPG#148]
Forge version: 
DivineRPG version: 1.12.2 latest.
https://gist.github.com/FrozenYT/e393c340c089dcc56a1d1a6b456f8ea9

Steps to reproduce:
1. Take weapon Evernight.
2. Start shooting on divinerpg: zone
3. Hope you hit the EntityDivineArrow.

What I expected to happen:
Kill mob. Perhaps the map broke due to the fact that a friend on the local server shot in the mob, and hit the EntityDivineArrow.

What happened instead:
Crash....

**Comment by AstralScourge** [comment]
Fixed in b6d1241. By the way you're not on the latest which is 1.6.4.1

**Comment by FrozenYT** [comment]
I have my own version of DivineRPG)

**Comment by NicosaurusRex99** [comment]
Well without our patch your version will be broken
