### ISSUE TITLE
Crash with DynamicStealth and TickCentral

### ISSUE THREAD

**Issue by vrnRaptor** [NicosaurusRex99/DivineRPG#151]
Forge version: 
DivineRPG version: DivineRPG-1.6.4.1.jar
Link to crash log: [gist](https://gist.github.com/vrnRaptor/41f305ca5cb03e7f9920c1d28462ce52#file-crash-txt)

Steps to reproduce:
1. Install DynamicStealth-1.12.2.103.jar.
2. Install TickCentral-2.6.jar.
3. Provoke aggression from the divinerpg:frost, divinerpg:kobblin or divinerpg:pumpkin_spider.

**Comment by AstralScourge** [comment]
Can you try it without Tick Central/Lag Goggles? The crash log mentions it

**Comment by vrnRaptor** [comment]
I installed only these three mods, with two of them everything works.

**Comment by AstralScourge** [comment]
Can you elaborate on what you mean, or just post an entire log?

**Comment by vrnRaptor** [comment]
I updated the crashreport. Tick Central required for LagGoggles. FantasticLib required for DynamicStealth. I mean works with DivineRPG + LagGoggles or DivineRPG + DynamicStealth. Don't works with DivineRPG + LagGoggles + DynamicStealth.
Fix. Crash with DivineRPG + DynamicStealth + TickCentral.

**Comment by AstralScourge** [comment]
Can you post the log when frosts cause a crash?

**Comment by vrnRaptor** [comment]
> Can you post the log when frosts cause a crash?

Gist updated.

**Comment by AstralScourge** [comment]
Anyway TickCentral uses ASM to add a "true on update" method, which is probably messing with things. It might be fine on its own but I imagine it's a weird combination of that and whatever Dynamic Stealth does causing the issue
