### ISSUE TITLE
FPS Lag

### ISSUE THREAD

**Issue by iiNovaTV** [NicosaurusRex99/DivineRPG#19]
FPS won't go above 10-15 in the Divine RPG dimensions (Iceika, Eden, Wildwood, Apalachia, Slythern, and Mortum)

**Comment by NicosaurusRex99** [comment]
Can i get your PC specs?
Processor: 
Ram: 
Graphics Card:
Windows: 

(The following can be done using this mod https://minecraft.curseforge.com/projects/modlister)
Mod List:

**Comment by iiNovaTV** [comment]
i7 4790k
16gb
MSI GTX 970
Windows 10

I have a lot of mods installed alongside Divine RPG so I did some testing by trial and error isolating mods with Divine RPG. I found that the mod "Biomes O' Plenty" caused the Divine RPG Dimension lagging. Without that mod, Divine RPG dimensions worked fine.

**Comment by krwminer** [comment]
Thanks for providing more information.

**Comment by iiNovaTV** [comment]
> Thanks for providing more information.

Is this an issue that will likely be fixed any time soon?

**Comment by iiNovaTV** [comment]
![2019-04-28_13 34 58](https://user-images.githubusercontent.com/48294907/56868023-d632d580-69ba-11e9-8ba8-90d1061a0188.png)
![2019-04-28_13 37 17](https://user-images.githubusercontent.com/48294907/56868024-d7fc9900-69ba-11e9-9c9d-9c7912110708.png)

(These debugs are being sent right after running around Iceika for a few minutes)

[debug.log](https://github.com/NicosaurusRex99/DivineRPG/files/3125275/debug.log)
[debug-1.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125276/debug-1.log.gz)
[debug-2.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125277/debug-2.log.gz)
[debug-3.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125278/debug-3.log.gz)
[debug-4.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125279/debug-4.log.gz)
[debug-5.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125280/debug-5.log.gz)

**Comment by NicosaurusRex99** [comment]
After further investigation i notice 3 potential candidates
Particles - Snow from iceika (display_update)
Tick lag (possibly mob ai)
GameRenderer (cant do much about this one except make your window smaller)

![2019-04-29_13 11 18](https://user-images.githubusercontent.com/11579935/56875582-165c8b80-6a81-11e9-98ba-497232e80ecc.png)
![2019-04-29_13 13 07](https://user-images.githubusercontent.com/11579935/56875583-165c8b80-6a81-11e9-9e04-1177ffc430a0.png)
![2019-04-29_13 14 29](https://user-images.githubusercontent.com/11579935/56875584-165c8b80-6a81-11e9-8414-b215ba2a0760.png)
![2019-04-29_13 14 33](https://user-images.githubusercontent.com/11579935/56875585-165c8b80-6a81-11e9-8a60-a604f0de7f4b.png)
![2019-04-29_13 15 02](https://user-images.githubusercontent.com/11579935/56875586-16f52200-6a81-11e9-99d2-11310f013bf9.png)
![2019-04-29_13 15 42](https://user-images.githubusercontent.com/11579935/56875587-16f52200-6a81-11e9-8ffd-f765fc98d5aa.png)
![2019-04-29_13 16 27](https://user-images.githubusercontent.com/11579935/56875588-16f52200-6a81-11e9-9399-66c8a21e8057.png)

**Comment by NicosaurusRex99** [comment]
@iiNovaTV please do this and then give me feedback. https://youtu.be/wMiZjK1kKC8

**Comment by NicosaurusRex99** [comment]
Please try allocate 8 threads. (what your cpu can handle) (the JVM ARG is -XX:ParallelGCThreads=8)

**Comment by NicosaurusRex99** [comment]
using the debug tool i can see that roughly 98% of events are tick related so some feature in either mod is ticking in the divine dimensions
