### ISSUE TITLE
Shooting an arrow from the "ender bow" crashes the game.

### ISSUE THREAD

**Issue by iiNovaTV** [NicosaurusRex99/DivineRPG#21]
When trying to release and arrow from an ender bow, the game crashes.

**Comment by iiNovaTV** [comment]
The same thing occurs with the bluefire bow.

**Comment by NicosaurusRex99** [comment]
Can you send some debug.log files please

**Comment by iiNovaTV** [comment]
This is my crash message:

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.item.ItemBow.func_185060_a(Lnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack; from class naturix.divinerpg.objects.items.base.ItemModBow

I also attached my crash report.
[crash-2019-04-28_13.15.07-client.txt](https://github.com/NicosaurusRex99/DivineRPG/files/3125234/crash-2019-04-28_13.15.07-client.txt)

**Comment by iiNovaTV** [comment]
Here is all of my debugs (sending these right after crashing from shooting an ender bow)
[debug-5.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125238/debug-5.log.gz)
[debug.log](https://github.com/NicosaurusRex99/DivineRPG/files/3125239/debug.log)
[debug-1.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125240/debug-1.log.gz)
[debug-2.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125241/debug-2.log.gz)
[debug-3.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125242/debug-3.log.gz)
[debug-4.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/3125243/debug-4.log.gz)

**Comment by krwminer** [comment]
What version of Forge are you using? You have to use the latest version. Forge made some changes in the Bow that made it incompatible between versions.

**Comment by krwminer** [comment]
I just checked, you are using 2768. It will not work. Try using 2836.

**Comment by krwminer** [comment]
I will close this for now and re-open if you are still having a problem with the latest version of Forge.
