### ISSUE TITLE
Frost Chest open/close animation seems to be Client only

### ISSUE THREAD

**Issue by krwminer** [NicosaurusRex99/DivineRPG#26]

**Comment by NicosaurusRex99** [comment]
U mean like on a server you open it and it doesnt move or you can open it but the close doesnt occur?

**Comment by krwminer** [comment]
The person accessing the chest can see the lid open and close but other people on the server do not see the animation of the lid.

**Comment by krwminer** [comment]
Fixed in https://github.com/NicosaurusRex99/DivineRPG/commit/85e89193a6df943a34dcc0a71199350cfdf50c0c

**Comment by krwminer** [comment]
Still have not fixed it yet.

**Comment by krwminer** [comment]
Fixed in https://github.com/NicosaurusRex99/DivineRPG/commit/63e894a48dc83921e8b69592e4c5cf537698ace6
(This time for sure!)
