### ISSUE TITLE
Skeleman trades borked

### ISSUE THREAD

**Issue by NicosaurusRex99** [NicosaurusRex99/DivineRPG#27]
When Trading with skeleman on a server it always gives the helmet.

**Comment by krwminer** [comment]
Did this break when I made the last change to the DivineVillager?
I will test when I can.

**Comment by NicosaurusRex99** [comment]
i am unsure but i just know its happening

**Comment by krwminer** [comment]
Fixed in https://github.com/NicosaurusRex99/DivineRPG/commit/73cbd12a79f2af115f746150dd4ce4ee1771e76d
