### ISSUE TITLE
couple bugs I found

### ISSUE THREAD

**Issue by the-fallen-mango** [NicosaurusRex99/DivineRPG#28]
Deathcryx make no sound (Not sure if they are meant to)
Iceika loads very slowly.
Eden has has partially complete chunks sometimes
Deathhound make no sound (Not sure if they are meant to)
Dramix makes no sound (Not sure if they are meant to)

**Comment by NicosaurusRex99** [comment]
The only issue i believe we are unaware of is the eden chunks

**Comment by the-fallen-mango** [comment]
I was stupid and forgot to take a screenshot. If I come across it again I will make sure to take one.

**Comment by krwminer** [comment]
I think all the mobs you mention are from Arcana, which is not done yet.

**Comment by NicosaurusRex99** [comment]
Closing for clarity. @the-fallen-mango can you create another issue if the eden chunk issue reoccurs
