### ISSUE TITLE
xp level disapears when you go to DivineRPG's worlds

### ISSUE THREAD

**Issue by E1ZY** [NicosaurusRex99/DivineRPG#33]
Forge version: 1.12.2 latest
DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar)
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. Get experience level
2. Go to  one of DivineRPG's worlds

What I expected to happen: 

What happened instead: experience level disappeared when I went to Mortum. But when I get more experience level returned 

Potential fix:

**Comment by NicosaurusRex99** [comment]
Fixed in 1558bc3
