### ISSUE TITLE
Angelic armor prevent other ways to fly

### ISSUE THREAD

**Issue by Oshi41** [NicosaurusRex99/DivineRPG#37]
Draconic armor or EE2 rings not working
As my investigations are correct, the reason in armorsetevent

**Comment by NicosaurusRex99** [comment]
It is because of the way we cancel flight.. we need a less invasive method of flight cancelation

**Comment by Oshi41** [comment]
@NicosaurusRex99 
Yep
I looked at Draconic Evolution, I think I have a solution
You can assign bug to me
