### ISSUE TITLE
General's Staff and Merik's Missile not working now

### ISSUE THREAD

**Issue by Oshi41** [NicosaurusRex99/DivineRPG#43]
This is no crushes (I hope)
They are just not working

**Comment by Oshi41** [comment]
General's saff is fixed
But we need to make a model indicating that missle is launching

**Comment by krwminer** [comment]
Fixed in https://github.com/NicosaurusRex99/DivineRPG/commit/4c15a31e05694e6db70256c9caa03a31bab68356
