### ISSUE TITLE
Arcana portal block render

### ISSUE THREAD

**Issue by Oshi41** [NicosaurusRex99/DivineRPG#45]
![image](https://user-images.githubusercontent.com/29630406/63251738-fd1d5c00-c276-11e9-9d51-e9fe49f2ff32.png)

**Comment by NicosaurusRex99** [comment]
Wont matter because the second the portal frame gets destroyed the block is removed. so survival players wont see the render bug

**Comment by Oshi41** [comment]
It is a portal frame, actually

**Comment by Oshi41** [comment]
And a Deamon Brambles
![image](https://user-images.githubusercontent.com/29630406/63252974-96e60880-c279-11e9-8f2d-2c5784e0265e.png)
