### ISSUE TITLE
Arcana portal block (actual portal not frame) render bug

### ISSUE THREAD

**Issue by AstralScourge** [NicosaurusRex99/DivineRPG#50]
When placing down arcana portal block in creative it makes the adjacent side of adjacent blocks invisible and you can see through them until the void or the next gap. This affects any side of a block touching the portal, including the block below and directly above, and multiple at the same time.

It should be noted that this doesn't affect the frame or similar blocks like the end portal block, so this will not happen in survival. However I'll post it here anyways

https://cdn.discordapp.com/attachments/612350548167098389/614563022597521409/ugly.PNG
https://cdn.discordapp.com/attachments/612350548167098389/614563019891933184/ugly2.PNG
https://cdn.discordapp.com/attachments/612350548167098389/614563471656222742/ugly3.PNG

**Comment by NicosaurusRex99** [comment]
Fixed in a09fb02.
![2019-08-24_13 09 13](https://user-images.githubusercontent.com/11579935/63632192-004a8a80-c671-11e9-92a9-523e90629996.png)
