### ISSUE TITLE
Ayeraco Crash

### ISSUE THREAD

**Issue by masterbobli** [NicosaurusRex99/DivineRPG#70]
Forge version: 2801
DivineRPG version: divinerpg-1.12.2.21.jar
Link to crash log if applicable: [Link](https://pastebin.com/sBHM0BMP)

Steps to reproduce:
1. Launch the game and join any world
2. Spawn any type of Ayeraco using spawn egg
3. See error

What I expected to happen:
An Ayeraco was spawned and nothing else would happen.

What happened instead:
The game crashed immediately after the mob was spawned.

Potential fix:
None.

**Comment by NicosaurusRex99** [comment]
@krwminer should we just remove the ayeraco spawn egg so they must be spawned by the horde horn?

**Comment by NicosaurusRex99** [comment]
No im suggesting we register the entity without a spawn egg

**Comment by masterbobli** [comment]
I apologize for my misinterpretation.

**Comment by NicosaurusRex99** [comment]
This has already been fixed btw.. Fixed in d6a600e
