### ISSUE TITLE
Behemoth texture missing

### ISSUE THREAD

**Issue by masterbobli** [NicosaurusRex99/DivineRPG#71]
Forge version: 2801
DivineRPG version: divinerpg-1.12.2.21.jar
Link to crash log if applicable: N/A

Steps to reproduce:
1. Launch the game
2. Spawn a behemoth
3. See error

What I expected to happen:
The behemoth has it's own

What happened instead:
The texture of this mob uses the missing texture from Minecraft.

Potential fix:
Unknown

**Comment by AstralScourge** [comment]
fixed in next build
