### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by coldfeudal** [NicosaurusRex99/DivineRPG#77]
Forge version: 1.12.2 - 14.23.5.2847 (server)
DivineRPG version: divinerpg-1.12.2.0-sources.jar (built on 7 Dec)
Link to crash log: https://gist.github.com/caribhunt/d94b6275651deacdf0f33f18fa337aa2

Don't know the reason, tried deleting ralistic item drops, but got the same

**Comment by NicosaurusRex99** [comment]
New beta released, please test this again

**Comment by NicosaurusRex99** [comment]
im going to close this issue but if it occurs again please reopen it
