### ISSUE TITLE
[1.12.2] Mefalith having no texture

### ISSUE THREAD

**Issue by Zack7292** [NicosaurusRex99/DivineRPG#81]
Forge version: 1.12.2 - 14.23.5.2847

DivineRPG version: divinerpg-1.12.2.15.jar

Steps to reproduce:
1. spawn a megalith 
2. seeing the lack of texture
What I expected to happen:
seeing a texture
What happened instead:
there we're no texture
Potential fix:
adding a texture or setting it correctly

**Comment by NicosaurusRex99** [comment]
Fixed in 9ff773d
![2020-02-26_11 16 54](https://user-images.githubusercontent.com/11579935/75301219-1e947b80-588a-11ea-9741-f4182b65262d.png)
