### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Zack7292** [NicosaurusRex99/DivineRPG#82]
Forge version: 1.12.2 - 14.23.5.2847
DivineRPG version: divinerpg-1.12.2.15.jar
Link to crash log if applicable: https://pastebin.com/m3itykEj

Steps to reproduce:
1. idk i rand while testing all the mobs one after another

What I expected to happen:
not crashing
What happened instead:
i crash
Potential fix:
making it not crash?

**Comment by Zack7292** [comment]
just find out it happened when i spawn a "DreamWrecker"

**Comment by NicosaurusRex99** [comment]
already working on the fix

**Comment by NicosaurusRex99** [comment]
Fixed in 30725d4
