### ISSUE TITLE
Mobs animation equipment when hit does not connect

### ISSUE THREAD

**Issue by MagicMaxcer** [NicosaurusRex99/DivineRPG#83]
Forge version: 
DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar)
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

Steps to reproduce:
1. hit a mob in this mod that is holding something 
2. dust lily and bramble are not planted there just drops in the dimension 

What I expected to happen:
not connecting 

What happened instead:

Potential fix:

**Comment by MagicMaxcer** [comment]
Spawn Megalith -missing texture -Spawn Skythern Fiend -hit it

**Comment by NicosaurusRex99** [comment]
Megalith Fixed in 9ff773d
Skyfiend is new

**Comment by MagicMaxcer** [comment]
Skythern Dimension a bunch of dust bramble and lily drops

**Comment by NicosaurusRex99** [comment]
Plants fixed in 480a7b1

**Comment by NicosaurusRex99** [comment]
mob model Fixed in 2fd63a9
