### ISSUE TITLE
[1.12.2] Cyclops spawn abuse

### ISSUE THREAD

**Issue by Zack7292** [NicosaurusRex99/DivineRPG#85]
Forge version: 2847
DivineRPG version: DivineRPG-1.12.2-1.5.1
![image](https://user-images.githubusercontent.com/45187146/75596301-fe1d1a80-5a5d-11ea-96bc-809b04961088.png)

Steps to reproduce:
1.  wandering around

What I expected to happen:
seeing MAx 1 or 2 cyclops, not more cyclops then cows
What happened instead:
i've seen lots of cyclops
Potential fix:
making then spawn less

**Comment by darknightbacca** [comment]
You can change the spawn values of mobs for DivineRPG in the config, see if that fixes it.

**Comment by AstralScourge** [comment]
> 
> 
> You can change the spawn values of mobs for DivineRPG in the config, see if that fixes it.

Where did you get this? We do not have any mob spawn value configs

**Comment by NicosaurusRex99** [comment]
This is intended. we use the same spawn values as 1.7.10 divinerpg
