### ISSUE TITLE
fire fluid crash?

### ISSUE THREAD

**Issue by KyrusArkenseed137** [NicosaurusRex99/DivineRPG#87]
Forge version: 1.12.2-14.23.3.2655
DivineRPG version: divinerpg 1.12.2-1.5.2.jar
Link to crash log if applicable: https://gist.github.com/KyrusArkenseed137/8c5db8699b38229f9798359bf8fe91a0

Steps to reproduce:
1.  open game and try to open inventory

What I expected to happen: open the inventory

What happened instead: crashed to desktop.

Potential fix:

**Comment by NicosaurusRex99** [comment]
Was tar in your inventory?

**Comment by NicosaurusRex99** [comment]
Should be fixed in 2c63c7f

**Comment by KyrusArkenseed137** [comment]
there is nothing from divinerpg in my inventory, its a new world

**Comment by NicosaurusRex99** [comment]
The error was a no such method so i just replicated the method i was reaching inside the Block Class

**Comment by KyrusArkenseed137** [comment]
ah perfect, so redownload and it should be all fixed  Ill of course let you know of any other errors as i find them

**Comment by NicosaurusRex99** [comment]
When version 1.5.3 is released

**Comment by KyrusArkenseed137** [comment]
thank you kindly, i shall await patiently

**Comment by AstralScourge** [comment]
@KyrusArkenseed137 update your forge 1.12.2-14.23.3.2655 is incredibly out of date. Most "no such" errors are results of that. You need to be on at least 1.12.2-14.23.5.2768
