### ISSUE TITLE
Mortum Trees generating inside hills and Frozen tree not finished

### ISSUE THREAD

**Issue by velocityraptor-real** [NicosaurusRex99/DivineRPG#88]
Forge version: 
DivineRPG version: (this is the build number, Example: divinerpg-1.12.2.20.jar)
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

(The 3rd one might not be an issue, if this is intended)

Steps to reproduce:
1. Go to the mortum dimension
2. Go to spectatormode
3. Fly into a hill/mountain

1. Go to icekia
2. Break the Frozen Logs of one frozen tree

1. Type Sapling in search bar
2. Search for a icekia-related sapling

What I expected to happen:
No trees being inside hills/mountains

Brittle leaves breaking/disappearing, when Forzen log is removed from the tree

To have a sapling to grow the frozen tree

What happened instead:
Trees being inside hills/mountains

Brittle leaves did not disappear

No icekia-related sapling exists

Potential fix:
Update Tree generation in mortum

Make the Brittle leaves behave like leaves

Add a frozen sapling

![2020-03-17_19 15 44](https://user-images.githubusercontent.com/56190563/76888511-52a8fe00-6884-11ea-9112-b4890957ccdf.png)
![2020-03-17_19 16 25](https://user-images.githubusercontent.com/56190563/76888522-563c8500-6884-11ea-8d7f-5787fb57b60b.png)

**Comment by velocityraptor-real** [comment]
I don't know, how some of the letters got so big. sorry

**Comment by NicosaurusRex99** [comment]
Fixed mortum trees ecca962
Brittle leaves next
