### ISSUE TITLE
Vethea respawn issue

### ISSUE THREAD

**Issue by Eternaldoom** [NicosaurusRex99/DivineRPG#90]
When a player dies in Vethea, they respawn on the top layer (at the world spawn point), not at the portal.

**Comment by velocityraptor-real** [comment]
I can't chek, if this is fixed in the latest commit, because this ceaps appearing:
![error](https://user-images.githubusercontent.com/56190563/77420355-2df3df80-6dca-11ea-8d41-a0201b7f0259.PNG)
when I try to enter a singleplayer world

**Comment by NicosaurusRex99** [comment]
ill revert my change, the bug will be present but may fix that

**Comment by velocityraptor-real** [comment]
Don't revert the change. This error ocurred after updating my game to https://github.com/NicosaurusRex99/DivineRPG/commit/8cf999bf8a8a70a6f7ee0d4dd30a015a19e1c937
It is a Overworld error, I think...

**Comment by NicosaurusRex99** [comment]
Without having a paratiku spawned that wouldnt be the issue

**Comment by velocityraptor-real** [comment]
?

**Comment by NicosaurusRex99** [comment]
try the latest commit and tell me if that works

**Comment by velocityraptor-real** [comment]
ok

**Comment by velocityraptor-real** [comment]
Yes, I was able to enter a world

**Comment by NicosaurusRex99** [comment]
thanks for testing

**Comment by velocityraptor-real** [comment]
should I test vethea respawning?

**Comment by NicosaurusRex99** [comment]
nope. still an issue.

**Comment by velocityraptor-real** [comment]
Tried to enter a old world and the fatal error occurred again
Can't even enter the new world I was able to enter when creating

**Comment by velocityraptor-real** [comment]
It seems to me, thet the fatal error occurs rendomly
[2020-03-24-6.log.gz](https://github.com/NicosaurusRex99/DivineRPG/files/4375077/2020-03-24-6.log.gz)

**Comment by NicosaurusRex99** [comment]
@Oshi41 seems like an armor issue

**Comment by Oshi41** [comment]
Yes, seems like i's true
Assign it to myself

**Comment by velocityraptor-real** [comment]
The recent commit https://github.com/NicosaurusRex99/DivineRPG/commit/d877ab272d2f4168cdc5d1b877dafacce459a30b
seems to almost fix the world loading problem:
The old Error doesn't seem to appear again, but my game crashes because of a new error now.
[crash.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4381930/crash.txt)

**Comment by velocityraptor-real** [comment]
Still not working in https://github.com/NicosaurusRex99/DivineRPG/commit/2819a30df0cae3fdb0d7331f986d59c90d4cb7b4
[crash-2020-03-25_19.16.55-server.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4382703/crash-2020-03-25_19.16.55-server.txt)
[crash2.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4382709/crash2.txt)
[latest.log](https://github.com/NicosaurusRex99/DivineRPG/files/4382710/latest.log)

**Comment by NicosaurusRex99** [comment]
Ive moved the armor issue to its own issue #96
