### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by DerMart1** [NicosaurusRex99/DivineRPG#91]
Somehow my Bedrockium Armor doesnt provide the fire and blast resistance after a while.
Once i had poison from the cave spider and then fire protection wanished. But it does seam to have another or more different reasons. Would be nice if you could fix this issue because otherwise these armours are unnecessary. Greetings

**Comment by NicosaurusRex99** [comment]
This is a known issue but ill leave it open til its fixed

**Comment by NicosaurusRex99** [comment]
fixed in 5444535
