### ISSUE TITLE
Game crashes when trying to plant Hitchak

### ISSUE THREAD

**Issue by velocityraptor-real** [NicosaurusRex99/DivineRPG#92]
Forge version: 1.12.2-14.23.5.2846
DivineRPG version: 1.12.2-1.5.2
Link to crash log if applicable:
[crash-2020-03-22_09.42.08-client.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4364896/crash-2020-03-22_09.42.08-client.txt)

Steps to reproduce:
1. Play DivineRPG1.12.2-1.5.2
2. Get yourself a tar bucket, arcane grass and a seed you plant on arcane grass
3. Plant the seed on arcane grass next to tar

What I expected to happen:
A plant appearing.
What happened instead:
Game crashes
Potential fix:
I am playing on a modpack that also has tar from another mod.
--> Maybe oredic problem?

**Comment by NicosaurusRex99** [comment]
old issue. was fixed 6a1fb7c
