### ISSUE TITLE
Invisible mobs

### ISSUE THREAD

**Issue by spcmnk** [NicosaurusRex99/DivineRPG#93]
Forge version: 1.12.2-14.23.5.2846
DivineRPG version: 1.12.2-1.5.2
Link to crash log if applicable: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)

**Steps to reproduce**:
1. Find a large area for mob spawning (for example, twilight dimension)
2. Walk around this area and kill mobs in survival
3. There is a small chance that somebody is trying to kill you

**What I expected to happen**:
No invisible mobs spawning

**What happened instead**:
Invisible mobs are spawning and hitting you
![2020-03-23 18-29-31-min](https://user-images.githubusercontent.com/47331299/77334584-10753600-6d36-11ea-9f99-9a01010eaf9d.gif)

**Comment by AstralScourge** [comment]
Invisible mobs are caused by Optifine. Ranged weapons are capable of killing them and relogging will reveal them, but if they are that big of an issue research a solution yourself (may or may not exist) or remove Optifine.
