### ISSUE TITLE
Issues associated with Arcana Dimension

### ISSUE THREAD

**Issue by spcmnk** [NicosaurusRex99/DivineRPG#94]
1)Paratiku egg doesn't work and causes the game to crash
2)Can't interact with Arcana Dimension doors in survival
3)Incorrect door texture when placed
Forge version: 1.12.2-14.23.5.2846
DivineRPG version: 1.12.2-1.5.2
Link to crash log if applicable: 1)https://gist.github.com/spcmnk/862310b4714450643cafbad09758b725

Steps to reproduce:
1)1. Find Paratiku egg
2.Use Paratiku egg
3.Game crashes

2)1.Go to Arcana Dimension
2.Find a room including doors
3.Go to survival mode and Right-click it

3)1.Get a door from Arcana Dimension
2.Place it
 
What I expected to happen:

What happened instead:
1)The game crashed
2)Can't open Arcana Dimension doors in survival mode
3)
![2020-03-23_09 44 29](https://user-images.githubusercontent.com/47331299/77400361-1281d800-6dbc-11ea-8326-fc4d1bf98e14.png)

Potential fix:

**Comment by NicosaurusRex99** [comment]
Doors require keys
Paratiku is a bug that may be fixed by updating your forge to recommended (14.23.5.2768) but let us know if it doesnt
Doors model is new will look into it (may also be fixed by updating forge)

**Comment by spcmnk** [comment]
Where I can get these keys?

**Comment by velocityraptor-real** [comment]
Tested it in the newest build (1.5.3) and game doesn't crash, when spawning paratiku, but paratiku doesn't spawn. (forge1.12.2-14.23.5.2846)

**Comment by NicosaurusRex99** [comment]
> Where I can get these keys?

https://divine-rpg.fandom.com/wiki/Dungeon_Keys



> Tested it in the newest build (1.5.3) and game doesn't crash, when spawning paratiku, but paratiku doesn't spawn. (forge1.12.2-14.23.5.2846)

were the doors ok?

**Comment by velocityraptor-real** [comment]
(naturally) generated doors work perfectly in creative, but are not openable in survival, even with key.
manually placed down doors behaving very wierdly.

**Comment by spcmnk** [comment]
I can't open these doors even with keys

**Comment by NicosaurusRex99** [comment]
its likely that you are using the wrong key then @spcmnk

**Comment by velocityraptor-real** [comment]
> 
> 
> its likely that you are using the wrong key then @spcmnk



> 
> 
> (naturally) generated doors work perfectly in creative, but are not openable in survival, even with key.
> manually placed down doors behaving very wierdly.

In survival, the keys don't work

**Comment by NicosaurusRex99** [comment]
keys fixed here 7bbf87c

**Comment by spcmnk** [comment]
I have one question: Where I can find a dramix and parasecta altar? I can't find rooms with them.

**Comment by velocityraptor-real** [comment]
Question in DivineRPG discord please, this is a issue report, no DivineRPG helping chat

**Comment by velocityraptor-real** [comment]
Doors working now. You can close the issue.

**Comment by NicosaurusRex99** [comment]
Fixed door item 4da1f74

**Comment by NicosaurusRex99** [comment]
paratiku still

**Comment by NicosaurusRex99** [comment]
paratiku not fixed

**Comment by NicosaurusRex99** [comment]
Paratiku fixed 8cf999b
