### ISSUE TITLE
Health patch

### ISSUE THREAD

**Issue by Oshi41** [NicosaurusRex99/DivineRPG#95]
Forge version: forge-1.12.2-14.23.5.2846
DivineRPG version: 1.5.2 I guess
Link to crash log if applicable:
 [11:59:40] [Client thread/WARN]: Can't patch max mob health
what does that mean?

Steps to reproduce:
1. Run the game I guess

What I expected to happen:
Not to see log warning above

What happened instead:
I see log warning

Potential fix:
I believe reflection can't find the field.
Need to investigate

**Comment by velocityraptor-real** [comment]
Not DivineRPG1.5.2, https://github.com/NicosaurusRex99/DivineRPG/commit/9941eb2b7039c50d98e22e5818cb2c5123ca8f48
latest commit

**Comment by NicosaurusRex99** [comment]
wouldnt be  latest but would be current

**Comment by Oshi41** [comment]
Should use ObfuscationReflectionHelper

**Comment by Oshi41** [comment]
Sould be closed there 2819a30df0cae3fdb0d7331f986d59c90d4cb7b4
