### ISSUE TITLE
Armor crashes

### ISSUE THREAD

**Issue by NicosaurusRex99** [NicosaurusRex99/DivineRPG#96]
Forge version: 1.12.2 - 14.23.5.2768
DivineRPG version: 1.5.3 (built from source)
Link to crash log if applicable: 
https://github.com/NicosaurusRex99/DivineRPG/files/4382710/latest.log
https://github.com/NicosaurusRex99/DivineRPG/files/4382709/crash2.txt
https://github.com/NicosaurusRex99/DivineRPG/files/4382703/crash-2020-03-25_19.16.55-server.txt
Steps to reproduce:
1. Apparently just load up
Potential fix:

**Comment by velocityraptor-real** [comment]
@Oshi41 just tell me, when you want me to test your commits.
I am happy to help.

**Comment by velocityraptor-real** [comment]
I am getting an error trying to build commit https://github.com/NicosaurusRex99/DivineRPG/commit/a295e6929365aa9b30e5a01d8edaf3888067e053
:compileJava
C:\Users\velocityraptor\Public Modding\DivineRPG-1.12.2\build\sources\main\java\divinerpg\api\armorNew\MainArmorEvents.java:60: error: cannot find symbol
for <IPoweredArmor armor : DivineAPI.getPowerSetRegistry<>> {
                                                           ^
  symbol:   method getPowerSetRegistry<>
  location: class DivineAPI

**Comment by velocityraptor-real** [comment]
The error seems to be fixed partially:
I am able to join some worlds, but some old worlds are still unjoinable:
[Idon'twanttowork.txt](https://github.com/NicosaurusRex99/DivineRPG/files/4396866/Idon.twanttowork.txt)

**Comment by NicosaurusRex99** [comment]
yeah that is known and unavoidable

**Comment by NicosaurusRex99** [comment]
you can copy the region (to keep your world) and the playerdata folder into a new save and nothing will break.

**Comment by velocityraptor-real** [comment]
ok, I'll try

**Comment by Oshi41** [comment]
@velocityraptor-real 
Seems like u r using old mod version
For example there is no 'armorNew' package

As Nico described above u can copy region data to keep world data
