### ISSUE TITLE
Odd behavior of speed boost given by vethean armors

### ISSUE THREAD

**Issue by SofiaAViesti** [NicosaurusRex99/DivineRPG#99]
Odd behavior of speed boost given by vethean armors
(My honest apologies if this has already been taken care of, I'm unsure how to check)

Forge version: forge1.12.2-14.23.5.2847
DivineRPG version: 1.12.2-1.5.2
Link to crash log if applicable: None

Steps to reproduce:
1. Go to Vethea and have Demonic or Tormented full armor (with the mask in order to get the speed boost)
2. The speed boost may not be given immediately, which gets fixed by reloading the world.
3. Remove the armor pieces - or even leave Vethea altogether. The speed boost persists until you remove the pieces in Vethea *and* reload the world again.

What I expected to happen: Speed boost given/removed accordingly to wearing the armor / being in Vethea

What happened instead: Odd behaviors

Potential fix: In my understanding, there may be something different (than Shadow armor, for example) in the structure of these armors where they only *check* and thereby give or remove the buff *when you load the world*. Sorry if this doesn't help much.

**Comment by NicosaurusRex99** [comment]
@Oshi41 you dont lose speed boost when the vethean armor is removed

**Comment by Oshi41** [comment]
Fixed here
https://github.com/NicosaurusRex99/DivineRPG/commit/697934bfe54f863d9938062764150e67903b8e19
